language: node_js
node_js:
  - "node"
before_script:
  - "yarn type"
  - "yarn lint"
  - "yarn test --coverage"
env:
  - CODECOV_TOKEN="e50c2896-42e5-4643-9c97-7ff911dc37a3"
scripts:
  - npm install codecov -g
after_success:
  - bash <(curl -s https://codecov.io/bash) -t CODECOV_TOKEN
cache:
  directories:
  - node_modules